# Change these first
owner: Dynox-Host # Your GitHub username
repo: Status-Website # Your GitHub repository name

# Add your sites here
sites:
  - name: Main Website
    url: https://dynoxhost.ml
    icon: https://cdn.discordapp.com/attachments/811925478348029982/812451407562276874/image0.png
  - name: Panel
    url: https://panel.dynoxhost.tk
    icon: https://cdn.discordapp.com/attachments/811925478348029982/812451407562276874/image0.png
  - name: DE-01
    url: https://node.dynoxhost.tk:8080
    icon: https://cdn.discordapp.com/attachments/811925478348029982/812451407562276874/image0.png
    __dangerous__disable_verify_host: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 401
      - 404
      - 501
      - 502

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.dynoxhost.tk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  theme: ocean
  favicon: https://cdn.discordapp.com/attachments/811925478348029982/812451407562276874/image0.png
  # baseUrl: /upptime
  logoUrl: https://cdn.discordapp.com/attachments/811925478348029982/812451407562276874/image0.png
  name: Dynox Host
  introTitle: "Dynox **Nodes** & **Services** Status."
  introMessage: The status is in **Real Time**.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://dynoxhost.ml
    - title: Panel
      href: https://panel.dynoxhost.tk

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
